version: '2'
services:
  front:
    build: ./haproxy
    ports:
      - "80:80"
    links:
      - api
      - web
    networks:
      - inside
  web:
    build: .
    ports:
      - "9000:9000"
    networks:
      - inside
  codegen:
    build: ../mgp-codegen
    ports:
      - "3001:3001"
    networks:
      - inside
  api:
    build: ../mgpback
    ports:
      - "8080:8080"
    networks:
      - inside
    links:
      - mongo
      - neo
    environment:
      - MONGO_DB=mongo
      - NEO4J_DB=http://neo:7474
      - CODEGEN_HOST=http://codegen:3001/
    depends_on:
      - mongo
      - neo
  mongo:
    image: mongo
    ports:
    - "8081:27017"
    networks:
      - inside
  neo:
    image: neo4j
    ports:
      - "7878:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    networks:
      - inside
networks:
  inside:
