---
- name: mgp update git project
  git:
    repo: git@github.com:b4456609/mgp.git
    dest: "{{ work_dir }}"
    clone: yes
    update: yes
- name: build mgpback spring boot
  tags: back
  shell: ./gradlew bootRepackage
  args:
    chdir: "{{ work_dir }}/mgp-back"
